### PR TITLE
clarified responsbilities

### PR DESCRIPTION
**Pull request by martinduke**

### CODE REVIEW

**Comment by mirjak** [comment]
I guess so far usually it has been the IESG that decides about the start time or experiments with the start time, no...?

**Comment by martinduke** [comment]
> 
> 
> I guess so far usually it has been the IESG that decides about the start time or experiments with the start time, no...?

Yeah, but that's because there's no policy. I think the point of the draft is to allow the LLC to implement this without a lot of deliberation

**Comment by mirjak** [comment]
I'd say the distinction criteria is if it is a question about the meeting organisation that impacts participants/productivity or IETF finances. And I don't think there is any financial impact in selecting the starting time of an online meeting. So this would also clearly fall in the responsibility of the IESG for me and not the LLC board. I don't think it matters for the question of who is responsible if there is an agreed policy or not.

Also, previously, experiments where we started the in-person meeting at 10am rather than at 9am were also initiated and decided by the IESG.

**Comment by martinduke** [comment]
Alright, works for me.

**Comment by mirjak** [comment]
OBE

**Pull request closed without merging**
